[project]
name = "nexus-fde-logistics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "robinsonjavaine43", email = "robinsonjavaine43@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.4.0,<2.0.0",
    "langchain-core>=1.6.3,<2.0.0",
    "langchain-ollama>=1.1.0,<2.0.0",
    "pydantic>=2.13.5",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.3",
]

[project.scripts]
nexus-fde-logistics = "nexus_fde_logistics:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
